export const TITLES = {
  BISHOP: "Bishop",
  CAPT: "Capt.",
  DR: "Dr.",
  FATHER: "Father",
  GEN: "Gen.",
  MISS: "Miss",
  MR: "Mr.",
  MRS: "Mrs.",
  PASTOR: "Pastor",
  RABBI: "Rabbi",
  REVEREND: "Reverend",
  SIR: "Sir",
} as const;


export const ACCOUNT_LIST = [
  {
    account_id: "5363662837514240",
    label: "Agent  1 - saurabh@thesqua.re - APS Demo Account",
  },
  {
    account_id: "6603633791598592",
    label: "Agent 2 - apsdemo2023@gmail.com - APS Demo Account",
  },
  {
    account_id: "5917376618954752",
    label: "abhi - ac1@gmail.com - APS Demo Account",
  },
  {
    account_id: "6663015422230528",
    label: "fet - ac1111@gmail.com - APS Demo Account",
  },
  {
    account_id: "4641994670342144",
    label: "- - APS Demo Account",
  },
] as const;

export const TAXSET_LIST = [
  {
    account_id: "6545823393382400",
    label: "Mandate Tax",
  },
  {
    account_id: "6327093392572416",
    label: "Service Tax",
  },
  {
    account_id: "5935555223224320",
    label: "Taxes",
  },
  {
    account_id: "4592526247854080",
    label: "per_person_including_children",
  },
  {
    account_id: "6648011293720576",
    label: "Adult child tax test",
  },
  {
    account_id: "5162720023281664",
    label: "Service Tax + City Tax",
  },
  {
    account_id: "5898769540317184",
    label: "City + Service + Green",
  },
] as const;

export const SOURCE_LIST_FOR_CREATE_TASK=[
  { value: "external", label: "External" },
  { value: "internal", label: "Internal Team" },
]

export const PRIORITY_LIST_FOR_CREATE_TASK=[
  { value: "emergency", label: "Emergency/Essential" },
  { value: "low", label: "Low" },
  { value: "medium", label: "Medium" },
  { value: "high", label: "High" },
]

export const PAYMENT_METHODS_LIST=[
  { value: "cash", label: "Cash" },
  { value: "upi", label: "UPI" },
  { value: "google-pay", label: "Google Pay" },
  { value: "credit-card", label: "Credit Card" },
  { value: "debit-card", label: "Debit Card" },
  { value: "paypal", label: "PayPal" },
  { value: "booking-channel", label: "Booking Channel" },
  { value: "bank-transfer", label: "Bank Transfer" },
  { value: "other", label: "Other" },
]
export const DNR_TYPE_LIST = [
  { value: "DNR APARTMENT EXIT", label: "DNR APARTMENT EXIT" },
  { value: "DNR DIRTY APARTMENT", label: "DNR DIRTY APARTMENT" },
  { value: "DNR EARLY CHECKIN", label: "DNR EARLY CHECKIN" },
  { value: "DNR ENGINEER VISIT", label: "DNR ENGINEER VISIT" },
  { value: "DNR LATE CHECKOUT", label: "DNR LATE CHECKOUT" },
  { value: "DNR MAINTENANCE REFURB", label: "DNR MAINTENANCE REFURB" },
  { value: "DNR MLOS RESTRICTION", label: "DNR MLOS RESTRICTION" },
  { value: "DNR OTHERS", label: "DNR OTHERS" },
  { value: "DNR PREP HOLD", label: "DNR PREP HOLD" },
  { value: "DNR SERVICE ISSUE", label: "DNR SERVICE ISSUE" },
  { value: "DNR SERVICE RECOVERY", label: "DNR SERVICE RECOVERY" },
  { value: "DNR VIEWING APARTMENT", label: "DNR VIEWING APARTMENT" },
  { value: "DNR PRE ONBOARDING", label: "DNR PRE ONBOARDING" },
] as const;


export const NATIONALITY_LIST = [
  { value: "afghan", label: "Afghan" },
  { value: "albanian", label: "Albanian" },
  { value: "algerian", label: "Algerian" },
  { value: "andorran", label: "Andorran" },
  { value: "angolan", label: "Angolan" },
  { value: "antiguans", label: "Antiguans" },
  { value: "argentinean", label: "Argentinean" },
  { value: "armenian", label: "Armenian" },
  { value: "australian", label: "Australian" },
  { value: "austrian", label: "Austrian" },
  { value: "azerbaijani", label: "Azerbaijani" },
  { value: "bahamian", label: "Bahamian" },
  { value: "bahraini", label: "Bahraini" },
  { value: "bangladeshi", label: "Bangladeshi" },
  { value: "barbadian", label: "Barbadian" },
  { value: "barbudans", label: "Barbudans" },
  { value: "batswana", label: "Batswana" },
  { value: "belarusian", label: "Belarusian" },
  { value: "belgian", label: "Belgian" },
  { value: "belizean", label: "Belizean" },
  { value: "beninese", label: "Beninese" },
  { value: "bhutanese", label: "Bhutanese" },
  { value: "bolivian", label: "Bolivian" },
  { value: "bosnian", label: "Bosnian" },
  { value: "motswana", label: "Motswana" },
  { value: "brazilian", label: "Brazilian" },
  { value: "bruneian", label: "Bruneian" },
  { value: "bulgarian", label: "Bulgarian" },
  { value: "burkinabe", label: "Burkinabe" },
  { value: "burundian", label: "Burundian" },
  { value: "cambodian", label: "Cambodian" },
  { value: "cameroonian", label: "Cameroonian" },
  { value: "canadian", label: "Canadian" },
  { value: "cape verdean", label: "Cape Verdean" },
  { value: "central african", label: "Central African" },
  { value: "chadian", label: "Chadian" },
  { value: "chilean", label: "Chilean" },
  { value: "chinese", label: "Chinese" },
  { value: "colombian", label: "Colombian" },
  { value: "comoran", label: "Comoran" },
  { value: "costa rican", label: "Costa Rican" },
  { value: "croatian", label: "Croatian" },
  { value: "cuban", label: "Cuban" },
  { value: "cypriot", label: "Cypriot" },
  { value: "czech", label: "Czech" },
  { value: "congolese", label: "Congolese" },
  { value: "danish", label: "Danish" },
  { value: "djibouti", label: "Djibouti" },
  { value: "dominican", label: "Dominican" },
  { value: "east timorese", label: "East Timorese" },
  { value: "ecuadorean", label: "Ecuadorean" },
  { value: "egyptian", label: "Egyptian" },
  { value: "salvadoran", label: "Salvadoran" },
  { value: "equatorial guinean", label: "Equatorial Guinean" },
  { value: "eritrean", label: "Eritrean" },
  { value: "estonian", label: "Estonian" },
  { value: "swazi", label: "Swazi" },
  { value: "ethiopian", label: "Ethiopian" },
  { value: "fijian", label: "Fijian" },
  { value: "finnish", label: "Finnish" },
  { value: "french", label: "French" },
  { value: "gabonese", label: "Gabonese" },
  { value: "gambian", label: "Gambian" },
  { value: "georgian", label: "Georgian" },
  { value: "german", label: "German" },
  { value: "ghanaian", label: "Ghanaian" },
  { value: "greek", label: "Greek" },
  { value: "grenadian", label: "Grenadian" },
  { value: "guatemalan", label: "Guatemalan" },
  { value: "guinea-bissauan", label: "Guinea-Bissauan" },
  { value: "guinean", label: "Guinean" },
  { value: "guyanese", label: "Guyanese" },
  { value: "haitian", label: "Haitian" },
  { value: "honduran", label: "Honduran" },
  { value: "hungarian", label: "Hungarian" },
  { value: "icelander", label: "Icelander" },
  { value: "indian", label: "Indian" },
  { value: "indonesian", label: "Indonesian" },
  { value: "iranian", label: "Iranian" },
  { value: "iraqi", label: "Iraqi" },
  { value: "irish", label: "Irish" },
  { value: "israeli", label: "Israeli" },
  { value: "italian", label: "Italian" },
  { value: "ivorian", label: "Ivorian" },
  { value: "jamaican", label: "Jamaican" },
  { value: "japanese", label: "Japanese" },
  { value: "jordanian", label: "Jordanian" },
  { value: "kazakhstani", label: "Kazakhstani" },
  { value: "kenyan", label: "Kenyan" },
  { value: "kuwaiti", label: "Kuwaiti" },
  { value: "kyrgyz", label: "Kyrgyz" },
  { value: "laotian", label: "Laotian" },
  { value: "latvian", label: "Latvian" },
  { value: "lebanese", label: "Lebanese" },
  { value: "mosotho", label: "Mosotho" },
  { value: "liberian", label: "Liberian" },
  { value: "libyan", label: "Libyan" },
  { value: "liechtensteiner", label: "Liechtensteiner" },
  { value: "lithuanian", label: "Lithuanian" },
  { value: "luxembourger", label: "Luxembourger" },
  { value: "malagasy", label: "Malagasy" },
  { value: "malawian", label: "Malawian" },
  { value: "malaysian", label: "Malaysian" },
  { value: "maldivan", label: "Maldivan" },
  { value: "malian", label: "Malian" },
  { value: "maltese", label: "Maltese" },
  { value: "marshallese", label: "Marshallese" },
  { value: "mauritanian", label: "Mauritanian" },
  { value: "mauritian", label: "Mauritian" },
  { value: "mexican", label: "Mexican" },
  { value: "micronesian", label: "Micronesian" },
  { value: "moldovan", label: "Moldovan" },
  { value: "monacan", label: "Monacan" },
  { value: "mongolian", label: "Mongolian" },
  { value: "moroccan", label: "Moroccan" },
  { value: "burmese", label: "Burmese" },
  { value: "mozambican", label: "Mozambican" },
  { value: "namibian", label: "Namibian" },
  { value: "nauruan", label: "Nauruan" },
  { value: "nepalese", label: "Nepalese" },
  { value: "dutch", label: "Dutch" },
  { value: "new zealander", label: "New Zealander" },
  { value: "ni-vanuatu", label: "Ni-Vanuatu" },
  { value: "nicaraguan", label: "Nicaraguan" },
  { value: "nigerien", label: "Nigerien" },
  { value: "north korean", label: "North Korean" },
  { value: "northern irish", label: "Northern Irish" },
  { value: "macedonian", label: "Macedonian" },
  { value: "norwegian", label: "Norwegian" },
  { value: "omani", label: "Omani" },
  { value: "pakistani", label: "Pakistani" },
  { value: "palauan", label: "Palauan" },
  { value: "panamanian", label: "Panamanian" },
  { value: "papua new guinean", label: "Papua New Guinean" },
  { value: "paraguayan", label: "Paraguayan" },
  { value: "peruvian", label: "Peruvian" },
  { value: "filipino", label: "Filipino" },
  { value: "polish", label: "Polish" },
  { value: "portuguese", label: "Portuguese" },
  { value: "qatari", label: "Qatari" },
  { value: "romanian", label: "Romanian" },
  { value: "russian", label: "Russian" },
  { value: "rwandan", label: "Rwandan" },
  { value: "kittian and nevisian", label: "Kittian and Nevisian" },
  { value: "saint lucian", label: "Saint Lucian" },
  { value: "samoan", label: "Samoan" },
  { value: "san marinese", label: "San Marinese" },
  { value: "sao tomean", label: "Sao Tomean" },
  { value: "saudi", label: "Saudi" },
  { value: "scottish", label: "Scottish" },
  { value: "senegalese", label: "Senegalese" },
  { value: "serbian", label: "Serbian" },
  { value: "seychellois", label: "Seychellois" },
  { value: "sierra leonean", label: "Sierra Leonean" },
  { value: "singaporean", label: "Singaporean" },
  { value: "slovakian", label: "Slovakian" },
  { value: "slovenian", label: "Slovenian" },
  { value: "solomon islander", label: "Solomon Islander" },
  { value: "somali", label: "Somali" },
  { value: "south african", label: "South African" },
  { value: "south korean", label: "South Korean" },
  { value: "spanish", label: "Spanish" },
  { value: "sri lankan", label: "Sri Lankan" },
  { value: "sudanese", label: "Sudanese" },
  { value: "surinamer", label: "Surinamer" },
  { value: "swedish", label: "Swedish" },
  { value: "swiss", label: "Swiss" },
  { value: "syrian", label: "Syrian" },
  { value: "taiwanese", label: "Taiwanese" },
  { value: "tajik", label: "Tajik" },
  { value: "tanzanian", label: "Tanzanian" },
  { value: "thai", label: "Thai" },
  { value: "togolese", label: "Togolese" },
  { value: "tongan", label: "Tongan" },
  { value: "trinidadian or tobagonian", label: "Trinidadian or Tobagonian" },
  { value: "tunisian", label: "Tunisian" },
  { value: "turkish", label: "Turkish" },
  { value: "tuvaluan", label: "Tuvaluan" },
  { value: "ugandan", label: "Ugandan" },
  { value: "emirian", label: "Emirian" },
  { value: "british", label: "British" },
  { value: "american", label: "American" },
  { value: "ukrainian", label: "Ukrainian" },
  { value: "uruguayan", label: "Uruguayan" },
  { value: "uzbekistani", label: "Uzbekistani" },
  { value: "venezuelan", label: "Venezuelan" },
  { value: "vietnamese", label: "Vietnamese" },
  { value: "welsh", label: "Welsh" },
  { value: "yemenite", label: "Yemenite" },
  { value: "zambian", label: "Zambian" },
  { value: "zimbabwean", label: "Zimbabwean" },
] as const;


