import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DevTokenSetter from "@/components/dev/DevTokenSetter";
import DevSessionSetter from "@/components/dev/DevSessionSetter";
import Header from "@/components/Header/Header";
import { UserProvider } from "@/contexts/UserContext";
import { ErrorProvider } from "@/contexts/ErrorContext";
import ErrorModal from "@/components/common/ErrorModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PMS - A Perfect Stay",
  description: "Generated by create next app",
  icons: "/favicon.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ErrorProvider>
          <UserProvider>
            {/* <DevSessionSetter /> */}
            <Header />
            {children}
            <ErrorModal />
            {/* <DevTokenSetter /> */}
          </UserProvider>
        </ErrorProvider>
      </body>
    </html>
  );
}
