import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import { UserProvider } from "@/contexts/UserContext";
import { ErrorProvider } from "@/contexts/ErrorContext";
import ErrorModal from "@/components/common/ErrorModal";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PMS - A Perfect Stay",
  description: "Generated by create next app",
  icons: "/favicon.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ErrorProvider>
          <UserProvider>
            <Header />
            {children}
            <ErrorModal />
          </UserProvider>
        </ErrorProvider>
        <Script
          src="https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"
          strategy="afterInteractive"
        />

        <Script id="google-translate-init" strategy="afterInteractive">
          {`
            window.__initGT = function() {
              new google.translate.TranslateElement(
                { pageLanguage: 'en', autoDisplay: false },
                'google_translate_element'
              );
            };

            function googleTranslateElementInit() {
              if (window.__gtUserReady) {
                if (window.__gtLang && window.__gtLang !== 'en') {
                  document.cookie = 'googtrans=/en/' + window.__gtLang + '; path=/; domain=.aperfectstay.ai';
                } else {
                  document.cookie = 'googtrans=; path=/; domain=.aperfectstay.ai; expires=Thu, 01 Jan 1970 00:00:00 GMT';
                }
                window.__initGT();
              } else {
                window.__gtScriptReady = true;
              }
            }
          `}
        </Script>
      </body>
    </html>
  );
}
